created: 2026-03-28T18:51:39.757Z
updated: 2026-03-28T19:11:26.909Z
update_count: 3
last_field: diagram
kind: nested-class
title: frontend
children:
  - chart-js
  - i18n-js
  - index-page
  - main-css
  - main-js
  - sector-js
  - stats-page
parentPath: []
