created: 2026-03-28T18:51:26.723Z
updated: 2026-03-28T18:51:56.909Z
update_count: 2
last_field: diagram
kind: nested-class
title: collector-layer
children:
  - crash-surge-data
  - fear-greed
  - index-price
  - market-data
  - noise-regime-data
  - sector-etf
  - sector-macro
parentPath: []
